'use strict';
const META_KEY='novel-library-meta-v1',DB_NAME='novel-library-files-v1',DB_STORE='texts',HANDLE_DB='novel-library-folders-v1';
let state={books:[]},activeBookId=null,activeChapterIndex=0,activeText='',folderHandle=null,folderQueue=Promise.resolve(),scrollTimer=0,restoringScroll=false,dirtyTextIds=new Set(),syncAllText=false,activeTags=new Set(),readerMode='read';
const $=id=>document.getElementById(id),fa=n=>new Intl.NumberFormat('fa-IR').format(n),makeId=()=>crypto.randomUUID();
function normalizeState(value){let books=Array.isArray(value?.books)?value.books:[];if(!books.length&&Array.isArray(value?.works))books=value.works.flatMap(work=>(work.books||[]).map(book=>({...book,author:book.author||work.author||'',tags:book.tags||[],reaction:book.reaction||'none'})));return{books:books.map(book=>({...book,id:book.id||makeId(),title:String(book.title||'بدون عنوان'),author:String(book.author||''),tags:[...new Set((Array.isArray(book.tags)?book.tags:[]).map(tag=>String(tag).trim()).filter(Boolean))],reaction:['like','dislike'].includes(book.reaction)?book.reaction:'none',chapters:(Array.isArray(book.chapters)?book.chapters:[]).map(chapter=>({hasText:!!chapter.hasText,percent:Number(chapter.percent)||0,done:!!chapter.done,scroll:Number(chapter.scroll)||0}))}))}}
function loadMeta(){try{state=normalizeState(JSON.parse(localStorage.getItem(META_KEY)||'{}'))}catch{state={books:[]}}}
function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(state))}
function openDB(name,store){return new Promise((resolve,reject)=>{const req=indexedDB.open(name,1);req.onupgradeneeded=()=>req.result.createObjectStore(store,{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function putText(id,text){const db=await openDB(DB_NAME,DB_STORE);return new Promise((resolve,reject)=>{const req=db.transaction(DB_STORE,'readwrite').objectStore(DB_STORE).put({id,text});req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
async function getText(id){const db=await openDB(DB_NAME,DB_STORE);return new Promise((resolve,reject)=>{const req=db.transaction(DB_STORE).objectStore(DB_STORE).get(id);req.onsuccess=()=>resolve(req.result?.text||'');req.onerror=()=>reject(req.error)})}
function textId(bookId,index){return`${bookId}:${index+1}`}function currentBook(){return state.books.find(book=>book.id===activeBookId)}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('appModal').showModal()}
function closeModal(){$('appModal').close();$('modalBody').replaceChildren()}
window.openModal=openModal;window.closeModal=closeModal;$('modalClose').onclick=closeModal;$('appModal').addEventListener('click',event=>{if(event.target===$('appModal'))closeModal()});$('modalBody').addEventListener('click',event=>{if(event.target.closest('[data-modal-close]'))closeModal();if(event.target.closest('[data-choose-folder]'))connectFolder(true)});
function showToast(text){const el=$('toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2100)}
function showPage(name,title){document.querySelectorAll('.page').forEach(page=>page.classList.toggle('hidden',page.id!==`page-${name}`));$('topTitle').textContent=title||'کتابخانه‌ی کتاب‌ها';document.body.classList.toggle('reader-mode',name==='reader');document.body.classList.toggle('reading-mode',name==='reader'&&readerMode==='read');window.scrollTo(0,0)}
function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function allTags(){return[...new Set(state.books.flatMap(book=>book.tags))].sort((a,b)=>a.localeCompare(b,'fa'))}
function renderTagOptions(){const query=$('tagSearch').value.trim().toLocaleLowerCase('fa'),tags=allTags().filter(tag=>tag.toLocaleLowerCase('fa').includes(query));$('tagOptions').innerHTML=tags.length?tags.map(tag=>`<label class="tag-option"><input type="checkbox" data-tag-option="${esc(tag)}" ${activeTags.has(tag)?'checked':''}><span>${esc(tag)}</span></label>`).join(''):'<span class="tag-empty">تگی پیدا نشد</span>'; $('selectedTags').innerHTML=[...activeTags].map(tag=>`<button type="button" class="selected-tag" data-remove-tag="${esc(tag)}" aria-label="حذف تگ ${esc(tag)}">${esc(tag)} ×</button>`).join('')}
function renderTagFilters(){const available=new Set(allTags());activeTags=new Set([...activeTags].filter(tag=>available.has(tag)));if(!activeTags.size){$('selectedTags').innerHTML=''}renderTagOptions()}
function renderDashboard(){renderTagFilters();const query=$('bookSearch').value.trim().toLocaleLowerCase('fa'),books=state.books.filter(book=>([...activeTags].every(tag=>book.tags.includes(tag)))&&(`${book.title} ${book.author} ${book.tags.join(' ')}`).toLocaleLowerCase('fa').includes(query)),list=$('worksList');if(!books.length){list.innerHTML=`<div class="empty">${state.books.length?'کتابی با این فیلتر پیدا نشد.':'هنوز کتابی اضافه نشده است.<br>برای شروع، «افزودن کتاب» را بزن.'}</div>`;return}list.innerHTML=books.map(book=>`<article class="work-card"><button type="button" class="book-open" data-open-book="${book.id}"><strong>${esc(book.title)}</strong><small>${esc(book.author||'نویسنده ثبت نشده')} · ${fa(book.chapters.length)} فصل</small></button><div class="book-row"><div class="book-tags">${book.tags.map(tag=>`<span class="book-tag">${esc(tag)}</span>`).join('')}</div><div class="book-actions"><button type="button" class="reaction ${book.reaction==='like'?'selected':''}" data-react="like" data-book="${book.id}" aria-label="${book.reaction==='like'?'برداشتن پسند':'پسندیدن'}" title="${book.reaction==='like'?'برداشتن پسند':'پسندیدن'}"><img src="./icons/like-${book.reaction==='like'?'filled':'empty'}.svg" alt=""></button><button type="button" class="reaction ${book.reaction==='dislike'?'selected':''}" data-react="dislike" data-book="${book.id}" aria-label="${book.reaction==='dislike'?'برداشتن نپسند':'نپسندیدن'}" title="${book.reaction==='dislike'?'برداشتن نپسند':'نپسندیدن'}"><img src="./icons/dislike-${book.reaction==='dislike'?'filled':'empty'}.svg" alt=""></button></div></div></article>`).join('')}
function chapterTemplate(count){return Array.from({length:count},()=>({hasText:false,percent:0,done:false,scroll:0}))}function tagsFromInput(value){return[...new Set(value.split(/[،,]/).map(tag=>tag.trim()).filter(Boolean))]}
function addBookDialog(){openModal('افزودن کتاب',`<form class="modal-form" id="newBookForm"><div class="field"><label for="authorInput">نام نویسنده</label><input id="authorInput" autocomplete="name"></div><div class="field"><label for="titleInput">نام کتاب</label><input id="titleInput" required></div><div class="field"><label for="chapterCountInput">تعداد فصل‌ها</label><input id="chapterCountInput" type="number" min="1" max="5000" value="1" required></div><div class="field"><label for="tagInput">تگ‌ها</label><input id="tagInput" placeholder="مثلاً فانتزی، ماجراجویی"></div><div class="modal-actions"><button class="button" type="button" data-modal-close>انصراف</button><button class="button primary" type="submit">ذخیره</button></div></form>`);$('newBookForm').onsubmit=async event=>{event.preventDefault();const count=Math.max(1,Math.min(5000,Number($('chapterCountInput').value)||1)),book={id:makeId(),title:$('titleInput').value.trim(),author:$('authorInput').value.trim(),tags:tagsFromInput($('tagInput').value),reaction:'none',chapters:chapterTemplate(count)};state.books.push(book);await persist();closeModal();renderDashboard();openChapters(book)}}
function editBookDialog(id){const book=state.books.find(item=>item.id===id);if(!book)return;openModal('ویرایش کتاب',`<form class="modal-form" id="editBookForm"><div class="field"><label for="editAuthor">نام نویسنده</label><input id="editAuthor" value="${esc(book.author)}"></div><div class="field"><label for="editTitle">نام کتاب</label><input id="editTitle" value="${esc(book.title)}" required></div><div class="field"><label for="editTags">تگ‌ها</label><input id="editTags" value="${esc(book.tags.join('، '))}" placeholder="مثلاً فانتزی، ماجراجویی"></div><div class="modal-actions"><button class="button" type="button" data-modal-close>انصراف</button><button class="button primary" type="submit">ذخیره</button></div></form>`);$('editBookForm').onsubmit=async event=>{event.preventDefault();book.author=$('editAuthor').value.trim();book.title=$('editTitle').value.trim();book.tags=tagsFromInput($('editTags').value);await persist();closeModal();renderDashboard();$('chapterBookTitle').textContent=book.title;$('chapterAuthor').textContent=book.author;$('readerBookTitle').textContent=book.title}}

function showFolderPrompt(){openModal('پوشه‌ی ذخیره‌سازی لازم است',`<div class="folder-prompt"><p>برای ذخیره‌ی متن فصل‌ها و پیشرفت مطالعه، یک پوشه انتخاب کن. اگر قبلاً پوشه‌ای داده‌ای می‌توانی دوباره همان را وصل کنی.</p><div class="modal-actions"><button class="button" type="button" data-modal-close>بعداً</button><button class="button primary" type="button" data-choose-folder>انتخاب پوشه</button></div></div>`)}
$('addButton').onclick=async()=>{let ready=false;try{ready=!!folderHandle&&await folderHandle.queryPermission({mode:'readwrite'})==='granted'}catch{}if(ready)addBookDialog();else showFolderPrompt()};$('bookSearch').oninput=renderDashboard;$('tagSearch').oninput=renderTagOptions;$('tagFilters').addEventListener('change',event=>{const input=event.target.closest('[data-tag-option]');if(!input)return;if(input.checked)activeTags.add(input.dataset.tagOption);else activeTags.delete(input.dataset.tagOption);renderTagFilters();renderDashboard()});$('tagFilters').addEventListener('click',event=>{const chip=event.target.closest('[data-remove-tag]');if(!chip)return;activeTags.delete(chip.dataset.removeTag);renderTagFilters();renderDashboard()});
$('worksList').addEventListener('click',async event=>{const open=event.target.closest('[data-open-book]');if(open){openChapters(state.books.find(book=>book.id===open.dataset.openBook));return}const reaction=event.target.closest('[data-react]');if(reaction){const book=state.books.find(item=>item.id===reaction.dataset.book);if(!book)return;book.reaction=book.reaction===reaction.dataset.react?'none':reaction.dataset.react;await persist();renderDashboard()}});
function openChapters(book){if(!book)return;activeBookId=book.id;$('chapterBookTitle').textContent=book.title;$('chapterAuthor').textContent=book.author;renderChapters(book);showPage('chapters',book.title);const next=book.chapters.findIndex(chapter=>!chapter.done),target=next<0?book.chapters.length-1:next;requestAnimationFrame(()=>document.querySelector(`[data-chapter="${target}"]`)?.scrollIntoView({block:'center',behavior:'smooth'}))}
function renderChapters(book){$('chapterList').innerHTML=book.chapters.map((chapter,index)=>{const cls=!chapter.hasText?'status-empty':chapter.done?'status-done':'status-writing';return`<button class="chapter-card ${cls}" data-chapter="${index}" aria-label="فصل ${fa(index+1)}، ${!chapter.hasText?'متن ندارد':chapter.done?'خوانده‌شده':`${fa(chapter.percent)}٪ خوانده‌شده`}"><i class="chapter-dot"></i><span class="chapter-detail"><span class="chapter-name">فصل ${fa(index+1)}</span><span class="chapter-meter"><span style="width:${chapter.done?100:chapter.percent}%"></span></span></span></button>`}).join('');$('chapterList').querySelectorAll('[data-chapter]').forEach(button=>button.onclick=()=>openReader(Number(button.dataset.chapter)))}
$('chapterBack').onclick=()=>showPage('dashboard');$('editChapterBook').onclick=()=>editBookDialog(activeBookId);
async function openReader(index){activeChapterIndex=index;const book=currentBook(),chapter=book?.chapters[index];if(!chapter)return;activeText=await getText(textId(book.id,index));$('readerBookTitle').textContent=book.title;$('readerChapterTitle').textContent=`فصل ${fa(index+1)} از ${fa(book.chapters.length)}`;$('chapterEditor').value=activeText;$('readingText').textContent=activeText;$('writeNotice').classList.toggle('hidden',!!activeText);$('saveText').classList.add('hidden');$('prevReaderChapter').disabled=index===0;$('nextReaderChapter').disabled=index===book.chapters.length-1;setReaderMode(activeText?'read':'write');showPage('reader',book.title);restoringScroll=true;requestAnimationFrame(()=>{const area=$('readArea');area.scrollTop=chapter.scroll||0;setTimeout(()=>{restoringScroll=false;updateReadProgress()},80)})}
function setReaderMode(mode){readerMode=mode;const writing=mode==='write';$('chapterEditor').classList.toggle('hidden',!writing);$('readArea').classList.toggle('hidden',writing);$('chapterImport').classList.toggle('hidden',!writing);$('modeIcon').src=writing?'./icons/open-book.svg':'./icons/pencil.svg';$('modeToggle').setAttribute('aria-label',writing?'رفتن به خواندن':'رفتن به نوشتن');$('modeToggle').title=writing?'خواندن':'نوشتن';$('saveText').classList.toggle('hidden',!writing);$('writeNotice').classList.toggle('hidden',writing?!!activeText:true);document.body.classList.toggle('reading-mode',!writing&&$('page-reader')&&!$('page-reader').classList.contains('hidden'))}
$('modeToggle').onclick=()=>{if(readerMode==='read'){$('chapterEditor').value=activeText;setReaderMode('write');return}if($('chapterEditor').value!==activeText){showToast('متن تغییر کرده؛ اول ذخیره‌اش کن.');return}if(!activeText){showToast('اول متن فصل را ذخیره کن.');return}setReaderMode('read');$('readingText').textContent=activeText};$('chapterEditor').oninput=()=>{$('writeNotice').classList.toggle('hidden',!!$('chapterEditor').value.trim())};
$('importChapter').onclick=()=>$('chapterFile').click();$('chapterFile').onchange=async()=>{const file=$('chapterFile').files?.[0];if(!file)return;try{let text=(await file.text()).replace(/^\uFEFF/,'');if(/\.md$/i.test(file.name))text=markdownToText(text);$('chapterEditor').value=text;setReaderMode('write');$('chapterEditor').focus();showToast('متن فایل بارگذاری شد؛ برای ذخیره، دکمه‌ی ذخیره را بزن.')}catch(error){console.error(error);showToast('خواندن فایل انجام نشد.')}finally{$('chapterFile').value=''}};
function markdownToText(value){return value.replace(/\r\n?/g,'\n').replace(/^\s*```[^\n]*\n?/gm,'').replace(/^\s*~~~[^\n]*\n?/gm,'').replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]+)\]\((?:[^()]|\([^()]*\))*\)/g,'$1').replace(/`([^`]*)`/g,'$1').replace(/^\s{0,3}#{1,6}\s*/gm,'').replace(/^\s*>\s?/gm,'').replace(/^\s*(?:[-+*]|\d+[.)])\s+/gm,'').replace(/^\s*(?:---+|___+|\*\*\*+)\s*$/gm,'').replace(/\|/g,' ').replace(/\[([^\]]+)\]\[[^\]]*\]/g,'$1').replace(/^\[[^\]]+\]:\s+\S+.*$/gm,'').replace(/\*\*([^*]+)\*\*|__([^_]+)__/g,'$1$2').replace(/~~([^~]+)~~/g,'$1').replace(/\*([^*]+)\*|_([^_]+)_/g,'$1$2').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,'').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
$('saveText').onclick=async()=>{const book=currentBook(),chapter=book.chapters[activeChapterIndex],value=$('chapterEditor').value;activeText=value;chapter.hasText=!!value.trim();await putText(textId(book.id,activeChapterIndex),value);dirtyTextIds.add(textId(book.id,activeChapterIndex));await persist();$('readingText').textContent=value;setReaderMode(value.trim()?'read':'write');renderChapters(book);showToast('متن فصل ذخیره شد')};
function updateReadProgress(){const book=currentBook(),chapter=book?.chapters[activeChapterIndex];if(!chapter||!activeText)return;const area=$('readArea'),max=area.scrollHeight-area.clientHeight,pct=max<=1?100:Math.min(100,Math.round(area.scrollTop/max*100));chapter.scroll=area.scrollTop;if(pct>=98)chapter.done=true;chapter.percent=chapter.done?100:pct;$('readerProgressFill').style.width=`${chapter.percent}%`;$('readerProgressFill').classList.toggle('done',chapter.done);$('readerPercent').textContent=chapter.done?'کامل خوانده شده':`${fa(chapter.percent)}٪`;clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>persist(),450)}$('readArea').onscroll=()=>{if(!restoringScroll)updateReadProgress()};
$('readerBack').onclick=()=>{const book=currentBook();renderChapters(book);showPage('chapters',book.title)};$('prevReaderChapter').onclick=()=>{if(activeChapterIndex>0)openReader(activeChapterIndex-1)};$('nextReaderChapter').onclick=()=>{const book=currentBook();if(activeChapterIndex<book.chapters.length-1)openReader(activeChapterIndex+1)};
function serializeState(){return JSON.parse(JSON.stringify(state))}async function persist(){saveMeta();if(folderHandle)queueFolderSave()}
async function fileAt(dir,path,create=false){const parts=path.split('/');let current=dir;for(const part of parts.slice(0,-1))current=await current.getDirectoryHandle(part,{create});return current.getFileHandle(parts.at(-1),{create})}async function writeFile(dir,path,content){const handle=await fileAt(dir,path,true),writer=await handle.createWritable();await writer.write(content);await writer.close()}async function readFile(dir,path){try{const handle=await fileAt(dir,path);return await(await handle.getFile()).text()}catch(error){if(error.name==='NotFoundError')return'';throw error}}
function queueFolderSave(){folderQueue=folderQueue.then(writeFolderData).catch(error=>{console.error(error);$('folderStatus').textContent='ذخیره در پوشه ناموفق بود؛ برای افزودن کتاب دوباره پوشه را وصل کن.'})}
async function writeFolderData(){if(!folderHandle)return;const permission=await folderHandle.queryPermission({mode:'readwrite'});if(permission!=='granted'){$('folderStatus').textContent='برای ذخیره در این پوشه، هنگام افزودن کتاب دوباره پوشه را وصل کن.';return}for(const book of state.books)for(let index=0;index<book.chapters.length;index++){const id=textId(book.id,index);if(!syncAllText&&!dirtyTextIds.has(id))continue;await writeFile(folderHandle,`chapters/${book.id}/${String(index+1).padStart(4,'0')}.txt`,await getText(id));dirtyTextIds.delete(id)}syncAllText=false;await writeFile(folderHandle,'library.json',JSON.stringify({format:'novel-library-v2',state:serializeState()},null,2));$('folderStatus').textContent=`پوشه‌ی «${folderHandle.name}» متصل است؛ متن‌ها و پیشرفت مطالعه در آن ذخیره می‌شوند.`}
function openFolderDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(HANDLE_DB,1);req.onupgradeneeded=()=>req.result.createObjectStore('handles',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}async function saveFolderHandle(handle){const db=await openFolderDB();return new Promise((resolve,reject)=>{const req=db.transaction('handles','readwrite').objectStore('handles').put({id:'main',handle});req.onsuccess=resolve;req.onerror=()=>reject(req.error)})}async function loadFolderHandle(){const db=await openFolderDB();return new Promise((resolve,reject)=>{const req=db.transaction('handles').objectStore('handles').get('main');req.onsuccess=()=>resolve(req.result?.handle||null);req.onerror=()=>reject(req.error)})}
async function readFolderData(handle){const raw=await readFile(handle,'library.json');if(!raw)return false;const saved=JSON.parse(raw);if(saved.format==='novel-library-v2'&&Array.isArray(saved.state?.books))state=normalizeState(saved.state);else if(saved.format==='novel-library-v1'&&Array.isArray(saved.state?.works))state=normalizeState(saved.state);else throw new Error('فایل فهرست کتاب‌ها معتبر نیست.');for(const book of state.books)for(let index=0;index<book.chapters.length;index++){const text=await readFile(handle,`chapters/${book.id}/${String(index+1).padStart(4,'0')}.txt`);if(text){await putText(textId(book.id,index),text);book.chapters[index].hasText=true}}saveMeta();return true}
async function connectFolder(continueToAdd=false){if(!window.showDirectoryPicker){showToast('انتخاب پوشه در این مرورگر در دسترس نیست؛ برنامه را در Chrome یا Edge و از localhost یا HTTPS باز کن.');return}try{const handle=await window.showDirectoryPicker({id:'novel-library-storage',mode:'readwrite'});let permission=await handle.queryPermission({mode:'readwrite'});if(permission!=='granted')permission=await handle.requestPermission({mode:'readwrite'});if(permission!=='granted'){showToast('اجازه‌ی دسترسی پوشه داده نشد.');return}folderHandle=handle;await saveFolderHandle(handle);const hasData=await readFolderData(handle);if(!hasData){syncAllText=true;await writeFolderData()}renderDashboard();$('folderStatus').textContent=`پوشه‌ی «${handle.name}» متصل است؛ متن‌ها و پیشرفت مطالعه در آن ذخیره می‌شوند.`;if(continueToAdd){closeModal();addBookDialog()}else showToast(hasData?'کتابخانه از پوشه بارگذاری شد.':'پوشه برای ذخیره آماده است.')}catch(error){if(error.name!=='AbortError'){console.error(error);showToast('اتصال پوشه انجام نشد.')}}}
async function initialize(){loadMeta();try{const handle=await loadFolderHandle();if(handle){folderHandle=handle;if(await handle.queryPermission({mode:'readwrite'})==='granted'){await readFolderData(handle);queueFolderSave()}else $('folderStatus').textContent='پوشه‌ی قبلی ثبت شده؛ با زدن افزودن کتاب دوباره آن را وصل کن.'}}catch(error){console.error(error)}renderDashboard();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{})}initialize();






